import numpy as np
import sys


#Load the modules we will need for the jobs
# shell.prefix()
shell.prefix("module load SLiM/5.1;")

#Directory where the simulations will take place
wrap_dir = '/net/feder/vol1/home/evromero/2025_hiv_linkage/data/slim_simulations/'
hxb2_file = '/net/feder/vol1/home/evromero/2025_hiv_linkage/data/hxb2_nuc_env.txt'
python_script_dir = '/net/feder/vol1/home/evromero/2025_hiv_linkage/bin/rule_scripts_simulation/'
slim_script_dir = '/net/feder/vol1/home/evromero/2025_hiv_linkage/src/paper_draft_04-13/04-30-2026_param_sweep/'

#The constants we will use for each run
DIR_NAME = '04-30-2026_sims/'
SLIM_SCRIPT_FILE = '04-30-2026_make_scripts.py'
SLIM_SCRIPT_TEMPLATE = '04-30-2026_sims.txt'
reps = range(5) #number of replicates
WINDOW_SIZE = 60
WINDOW_STEP = 20
IHH_CORE_FREQ_THRESH = 0.1
NE = 10000

#The population parameters we will sweep over
# mu = [10**(-7), 10**(-6), 10**(-5), 10**(-4)]
# mu = [10**(-7), 10**(-6), 10**(-5)]
mu = [10**(-6), 5*10**(-7), 10**(-7)]

selection_coeff = [0.1, 1, 5]

rho = [10**(-7), 10**(-6), 10**(-5)]


#Make a dictionary with the minimum number of origins for each number of origins
num_origins_list = [1, 2, 10, 20, 30, 50, 100]
min_num_origins_list = [1, 2, 5, 10, 20, 40, 80]
min_origins_dict = dict(zip(num_origins_list, min_num_origins_list))

# The patterns for the genotype and loci dataframes
# We want specific combinations of num_origins and min_num_origins
full_dir_pattern_gen = []
full_dir_pattern_loc = []
full_dir_pattern_pi = []
full_dir_pattern_ihh = []

for num_origins in num_origins_list:
    min_num_origins = min_origins_dict[num_origins]
    for rep in reps:
        full_dir_pattern_gen.append(wrap_dir + DIR_NAME + f"origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{{mu}}_sel_{{selection_coeff}}_rho_{{rho}}/analysis/FilteredGenotypes")
        full_dir_pattern_loc.append(wrap_dir + DIR_NAME + f"origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{{mu}}_sel_{{selection_coeff}}_rho_{{rho}}/analysis/FilteredLoci")
        full_dir_pattern_pi.append(wrap_dir + DIR_NAME + f"origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{{mu}}_sel_{{selection_coeff}}_rho_{{rho}}/origins_{num_origins}_min_{min_num_origins}_rep_{rep}_pi.csv")
        full_dir_pattern_ihh.append(wrap_dir + DIR_NAME + f"origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{{mu}}_sel_{{selection_coeff}}_rho_{{rho}}/origins_{num_origins}_min_{min_num_origins}_rep_{rep}_ihh_results.csv")

# Now we want to expand the patterns for the combinations of mu, selection_coeff, and rho
expanded_dir_pattern_gen = []
expanded_dir_pattern_loc = []
expanded_dir_pattern_pi = []
expanded_dir_pattern_ihh = []
for i in range(len(num_origins_list) * len(reps)):
    expanded_dir_pattern_gen.extend(expand(full_dir_pattern_gen[i],
        mu = mu,
        selection_coeff = selection_coeff,
        rho = rho))
    expanded_dir_pattern_loc.extend(expand(full_dir_pattern_loc[i],
        mu = mu,
        selection_coeff = selection_coeff,
        rho = rho))
    expanded_dir_pattern_pi.extend(expand(full_dir_pattern_pi[i],
        mu = mu,
        selection_coeff = selection_coeff,
        rho = rho))
    expanded_dir_pattern_ihh.extend(expand(full_dir_pattern_ihh[i],
        mu = mu,
        selection_coeff = selection_coeff,
        rho = rho))

# #Now go through and toss out all of the combos where rho is > mu 
# final_dir_pattern_gen = []
# final_dir_pattern_loc = []
# final_dir_pattern_pi = []
# final_dir_pattern_ihh = []
# for i in range(len(expanded_dir_pattern_gen)):
#     #Extract the mu and rho values from the directory pattern
#     dir_pattern = expanded_dir_pattern_gen[i]
#     mu_value = float(dir_pattern.split("mu_")[1].split("_sel")[0])
#     rho_value = float(dir_pattern.split("rho_")[1].split("/analysis")[0])
#     if rho_value <= mu_value:
#         final_dir_pattern_gen.append(expanded_dir_pattern_gen[i])
#         final_dir_pattern_loc.append(expanded_dir_pattern_loc[i])
#         final_dir_pattern_pi.append(expanded_dir_pattern_pi[i])
#         final_dir_pattern_ihh.append(expanded_dir_pattern_ihh[i])

# expanded_dir_pattern_gen = final_dir_pattern_gen
# expanded_dir_pattern_loc = final_dir_pattern_loc
# expanded_dir_pattern_pi = final_dir_pattern_pi
# expanded_dir_pattern_ihh = final_dir_pattern_ihh

#Targets are outputs and dependencies are inputs
rule all:
    input:
     expanded_dir_pattern_gen,
     expanded_dir_pattern_loc,
     expanded_dir_pattern_ihh,
     expanded_dir_pattern_pi

#This rule creates the directories and slim scripts for each simulation
rule set_up_dirs:
    input:
        SLIM_SCRIPT_TEMPLATE
    output: 
     wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/sim_origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}.slim"
    params:
        in_sim_template = SLIM_SCRIPT_TEMPLATE,
        out_sim_dir = wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/",
        NE = NE
    script:
        SLIM_SCRIPT_FILE

#This rule runs the slim script for each simulation
rule run_slim:
    input:
     wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/sim_origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}.slim"

    output:
     wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/slim_output.txt"

    shell: "slim " + wrap_dir + DIR_NAME + "origins_{wildcards.num_origins}_min_{wildcards.min_num_origins}_rep_{wildcards.rep}_mu_{wildcards.mu}_sel_{wildcards.selection_coeff}_rho_{wildcards.rho}/sim_origins_{wildcards.num_origins}_min_{wildcards.min_num_origins}_rep_{wildcards.rep}_mu_{wildcards.mu}_sel_{wildcards.selection_coeff}_rho_{wildcards.rho}.slim > " + \
            wrap_dir + DIR_NAME + "origins_{wildcards.num_origins}_min_{wildcards.min_num_origins}_rep_{wildcards.rep}_mu_{wildcards.mu}_sel_{wildcards.selection_coeff}_rho_{wildcards.rho}/slim_output.txt 2> " + \
            wrap_dir + DIR_NAME + "origins_{wildcards.num_origins}_min_{wildcards.min_num_origins}_rep_{wildcards.rep}_mu_{wildcards.mu}_sel_{wildcards.selection_coeff}_rho_{wildcards.rho}/slim_error.txt"

#This rule parses and makes dataframes of the slim output
rule format_slim_output:
    input: 
     wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/slim_output.txt"

    output:
     wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/analysis/FilteredGenotypes",
     wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/analysis/FilteredLoci"
    params:
        out_sim_dir = wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/",
        hxb2_file = hxb2_file


    script:
        python_script_dir + "format_slim_output.py"

#This rule calculates nucleotide diversity 
rule calc_pi_div:
    input:
        wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/analysis/FilteredGenotypes"
    output: 
        wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/origins_{num_origins}_min_{min_num_origins}_rep_{rep}_pi.csv"
    params:
        window_size = WINDOW_SIZE,
        window_step = WINDOW_STEP,
        hxb2_file = hxb2_file,
        num_origins = "{num_origins}",
        min_num_origins = "{min_num_origins}",
        rep = "{rep}",
        mu = "{mu}",
        selection_coeff = "{selection_coeff}",
        rho = "{rho}"
    script:
        python_script_dir + "pi_diversity_sim.py"

#This rule calculates the EHH linkage statistic
rule calc_linkage_ihh:
    input:
        wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/analysis/FilteredGenotypes",
        wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/analysis/FilteredLoci"
    output:
        wrap_dir + DIR_NAME + "origins_{num_origins}_min_{min_num_origins}_rep_{rep}_mu_{mu}_sel_{selection_coeff}_rho_{rho}/origins_{num_origins}_min_{min_num_origins}_rep_{rep}_ihh_results.csv"
    params:
        hxb2_file = hxb2_file,
        #Set allele frequency threshold to 0 for IHH calculations since we will filter based on core allele frequency
        allele_freq_thresh = 0,
        core_freq_thresh = IHH_CORE_FREQ_THRESH
    script:
        python_script_dir + "ihh_sim.py"
